# Generated by Django 4.1 on 2022-08-11 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('subtitle', models.TextField(max_length=120)),
                ('button_text', models.TextField(max_length=25)),
                ('link', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
