# Generated by Django 4.1 on 2022-08-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_card_button_text_alter_card_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
